version: "2"
linters:
  enable:
    # default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # additional linters
    - bodyclose
    - gosec
    - inamedparam
    - misspell
    - revive
    - sqlclosecheck
    - testifylint
    - forbidigo

  settings:
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print.*$
          msg: Do not commit print statements. Use slog instead.

run:
  timeout: 5m
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

