version: "2"
linters:
  enable:
    # default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # additional linters
    - bodyclose
    - gosec
    - inamedparam
    - misspell
    - revive
    - sqlclosecheck
    - testifylint
run:
  timeout: 5m
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

